name: Show Environment Values

on:
  workflow_dispatch:

jobs:
  show-values:
    runs-on: ubuntu-latest
    environment: DEVELOPMENT  # ðŸ‘ˆ Required to access env-specific secrets/vars

    steps:
      - name: Show Environment Variable
        run: echo "Env variable value is $ENV_VAR"
        env:
          ENV_VAR: ${{ vars.DEVELOPMENT }}

      - name: Show Environment Secret
        run: echo "Secret value is $SECRET_VAR"
        env:
          SECRET_VAR: ${{ secrets.DEVELOPMENT }}
